//Lipa

"Adya",
"Anilao",
"Anilao~Labac",
"Antipolo Del Norte",
"Antipolo Del Sur",
"Bagong Pook",
"Balintawak",
"Banaybanay",
"Barangay 12 (Pob.)",
"Bolbok",
"Bugtong Na Pulo",
"Bulacnin",
"Bulaklakan",
"Calamias",
"Cumba",
"Dagatan",
"Duhatan",
"Halang",
"Inosloban",
"Kayumanggi",
"Latag",
"Lodlod",
"Lumbang",
"Mabini",
"Malagonlong",
"Malitlit",
"Marauoy",
"Mataas Na Lupa",
"Munting Pulo",
"Pagolingin Bata",
"Pagolingin East",
"Pagolingin West",
"Pangao",
"Pinagkawitan",
"Pinagtongulan",
"Plaridel",
"Poblacion Barangay 1",
"Poblacion Barangay 10",
"Poblacion Barangay 11",
"Poblacion Barangay 2",
"Poblacion Barangay 3",
"Poblacion Barangay 4",
"Poblacion Barangay 5",
"Poblacion Barangay 6",
"Poblacion Barangay 7",
"Poblacion Barangay 8",
"Poblacion Barangay 9",
"Poblacion Barangay 9~A",
"Pusil",
"Quezon",
"Rizal",
"Sabang",
"Sampaguita",
"San Benito",
"San Carlos",
"San Celestino",
"San Francisco",
"San Guillermo",
"San Jose",
"San Lucas",
"San Salvador",
"San Sebastian (Balagbag)",
"Santo Nino",
"Santo Toribio",
"Sapac",
"Sico",
"Talisay",
"Tambo",
"Tangob",
"Tanguay",
"Tibig",
"Tipacan"
//===================================================================================================

//MALVAR

"Bagong Pook",
"Bilucao (San Isidro Western)",
"Bulihan",
"Luta Del Norte",
"Luta Del Sur",
"Poblacion",
"San Andres",
"San Fernando",
"San Gregorio",
"San Isidro East",
"San Juan",
"San Pedro I (Eastern)",
"San Pedro Ii (Western)",
"San Pioquinto",
"Santiago"
//===================================================================================================

//TANAUAN

"Altura~South",
"Altura Bata",
"Altura Matanda",
"Ambulong",
"Bagbag",
"Bagumbayan",
"Balele",
"Banadero",
"Banjo East",
"Banjo Laurel (Banjo West)",
"Bilog~Bilog",
"Boot",
"Cale",
"Darasa",
"Gonzales",
"Hidalgo",
"Janopol",
"Janopol Oriental",
"Laurel",
"Luyos",
"Mabini",
"Malaking Pulo",
"Maria Paz",
"Maugat",
"Montana (Ik~ik)",
"Natatas",
"Pagaspas",
"Pantay Bata",
"Pantay Matanda",
"Poblacion Barangay 1",
"Poblacion Barangay 2",
"Poblacion Barangay 3",
"Poblacion Barangay 4",
"Poblacion Barangay 5",
"Poblacion Barangay 6",
"Poblacion Barangay 7",
"Sala",
"Sambat",
"San Jose",
"Santor",
"Sulpoc",
"Suplang",
"Talaga",
"Tinurik",
"Trapiche",
"Ulango",
"Wawa",

//===================================================================================================

//STO TOMAS

"Barangay I (Pob.)",
"Barangay Ii (Pob.)",
"Barangay Iii (Pob.)",
"Barangay Iv (Pob.)",
"San Agustin",
"San Antonio",
"San Bartolome",
"San Felix",
"San Fernando",
"San Francisco",
"San Isidro Norte",
"San Isidro Sur",
"San Joaquin",
"San Jose",
"San Juan",
"San Luis",
"San Miguel",
"San Pablo",
"San Pedro",
"San Rafael",
"San Roque",
"Santa Ana",
"Santa Anastacia",
"Santa Clara",
"Santa Cruz",
"Santa Elena",
"Santa Maria",
"Santa Teresita",
"Santiago",
"San Vicente"